resolver: nightly-2020-11-23

compiler: ghc-8.10.2



packages:
# - '../../lmonad'
# - '../../lmonad-yesod'
# - 'dependencies/simplessh'
- 'bibifi-core'
- 'bibifi-webapp'
- 'bibifi-runner'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: 
# - lmonad-0.1.0.0
# - lmonad-yesod-1.0.0.0
# - network-ip-0.2.1.1
# - persistent-ratelimit-0.3.0.0
- git: https://github.com/nilehmann/LMonad.git
  commit: 259914462e56aef53bb726dabd0cb5ec058e4fcf
- git: https://github.com/nilehmann/LMonad-Yesod.git
  commit: 98be5887cc3c46b5a63a7144430127187813ce61
- git: https://github.com/jprider63/persistent-ratelimit.git
  commit: 4f3f9afc748453fb2beda00d339fc3a30ad6e7a3
- git: https://github.com/jprider63/simplessh.git
  commit: 9f8be6a732a527f4c8f4a6403c0f011dc517f666
- smtp-mail-0.2.0.0
- gitlab-haskell-0.1.5
- docker-0.6.0.2
- yesod-auth-oauth2-0.6.1.5@sha256:bc65e697ae622b80024ca22a7b9270bf64a8c96be8f6ac1d09ed3a1d1cbbde6e
#- yesod-auth-oauth2-0.1.6
# - data-textual-0.3.0.2
# - text-latin1-0.3
# - text-printer-0.4
# - data-checked-0.3
# - data-dword-0.3
# - data-endian-0.1
# - type-hint-0.1
# - data-bword-0.1
# - yesod-form-1.4.10 # ,data-dword-0.3, data-endian-0.1, data-textual-0.3.0.2, text-printer-0.4, type-hint-0.1]#, data-bword-0.1, atext-latin1-0.3]
# - git: https://github.com/jprider63/LMonad.git
#   commit: 9238df9fa56e59d6afc2c6515ea22ed5418f00e3
# - git: https://github.com/jprider63/LMonad-Yesod.git
#   commit: f3469f6175e12ea3b5b08629265986921db90c4e

# binah stuffs
#- github: binah-framework/binah
  #commit: 07961784e471af2787e996c578cb5716bdf35ba0

#- github: PLSysSec/frankie
  #commit: b9ee2c0f7667025d0d0ac3a43ded43d1d1d63c28

# LH stuff
#- liquid-base-4.14.1.0
#- liquidhaskell-0.8.6.5

#- text-format-0.3.2
#- Diff-0.3.4
#- optics-0.3@sha256:5f62fca47b01ce065bb999724b8cdd45e747537892ee00faeac4b4b20d821aee
#- optics-th-0.3.0.1@sha256:805ca7699d39aa01796eec394c4460def312bf59536f3d781adbf60ffdab288c

#- github: ucsd-progsys/liquid-fixpoint
  #commit: 58e3123f41dedd6082177303bb4b6bf4349edf46

#- github: ucsd-progsys/liquidhaskell
  #commit: ad7f0cf5b86cb62fa855f3392bfa34f65225c4ed
  #subdirs:
      #- .
      #- liquid-base
      #- liquid-ghc-prim



allow-newer: true

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

